version: '3.8'
services:
  db:
    image: postgres:15
    container_name: biblioteca_db
    environment:
      - POSTGRES_USER=biblioteca
      - POSTGRES_PASSWORD=biblioteca
      - POSTGRES_DB=biblioteca
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
